version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
            - mysql
            - redis
    php-fpm:
        container_name: php_laravel05_project
        environment:
            PHP_IDE_CONFIG: "serverName=laravel05"
        build:
          dockerfile: docker/php/Dockerfile
          context: .
        volumes:
            - ./:/var/www/html
        links:
            - mysql
            - redis
    mysql:
        container_name: laravel_db_project
        image: mariadb:10.3
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wd05
    redis:
        image: redis:latest
